name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0

      - name: make application.yml
        run: |
          mkdir -p ./src/main/resources
          echo "${{ secrets.APPLICATION }}" > ./src/main/resources/application.yml
        shell: bash

      - name: grdlew set permission
        run: chmod +x ./gradlew

      - name: Build with Gradle Wrapper
        run: ./gradlew build
        continue-on-error: true

      - name: Upload test report
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: test-report
          path: build/reports/tests/test

      - name: Upload build artifacts
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: my-app
          path: build/libs/*.jar

  dependency-submission:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0

  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Tar all files
        run: tar -cvf /tmp/295568076/Y2k8x8is8B.tar .

      - name: Copy files via SCP
        uses: appleboy/scp-action@v0.1.1
        with:
          host: yusuengdo.ddns.net
          username: tmdeh
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "/tmp/295568076/Y2k8x8is8B.tar"
          target: "/path/to/deploy/"

      - name: Execute remote SSH commands
        uses: appleboy/ssh-action@v0.1.1
        with:
          host: yusuengdo.ddns.net
          username: tmdeh
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            pkill -f 'java -jar' || true
            tar -xvf /path/to/deploy/Y2k8x8is8B.tar -C /path/to/deploy/
            nohup java -jar /path/to/deploy/save_me_seungdo_blog.jar &
